/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package unsafe_assignments

import kotlin.random.*

data class A(var a: Int = 0) {
    fun slow_assignment(value: Int) {
        if (Random.nextBoolean()) {
            Thread.sleep(1000)
        }

        a = value
    }
}

fun main(args: Array<String>) {
    val a = A()

    val t1 = Thread { a.slow_assignment(1) }
    val t2 = Thread { a.slow_assignment(2) }

    t1.start(); t2.start();
    t1.join(); t2.join();

    println("${a.a}")
}
