/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package unsafe_assignments

import kotlin.test.*

class AppTest {
    @Test fun testAHasValue() {
        val a = A()
        assertNotNull(a.a, "a.a should have a value")
    }

    @Test fun testACanAssign() {
        val a = A()
        assertEquals(0, a.a, "a.a should equal 0")

        a.slow_assignment(1)
        assertEquals(1, a.a, "a.a should equal 1 after assignment")
    }
}
